name: Kernel Config - A12 5.10

permissions:
  contents: write  # Allow writing to repository contents
  actions: write   # Allows triggering actions

on:
  workflow_call:
    inputs:
      susfs_version:
        required: false
        type: string
        default: "v1.5.12"

jobs:
  build-kernels-a12:
    strategy:
      fail-fast: false
      matrix:
        include:
        # Deprecated series (Android 12 - 5.10)
        - sub_level: "209"
          os_patch_level: "2024-05"
        - sub_level: "149"
          os_patch_level: "2022-12"
        - sub_level: "149"
          os_patch_level: "2023-01"
        - sub_level: "66"
          os_patch_level: "2021-11"
        - sub_level: "66"
          os_patch_level: "2021-12"
        - sub_level: "66"
          os_patch_level: "2022-01"

    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      android_version: "android12"
      kernel_version: "5.10"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      susfs_version: ${{ inputs.susfs_version }}

